apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
  labels:
    app: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: backend
        image: nelsonlopez69/ecommerce_backend
        ports:
        - containerPort: 8080